apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mavencache-test
spec:
  storageClassName: "jenkins-nfs-client"
  accessModes:
    - ReadWriteMany     
  resources:
    requests:
      storage: 10Gi
